### ISSUE TITLE
Skapa användarroller

### ISSUE THREAD

**Issue by Axelkarnebro** [Rickos99/D0018E#16]
Såsom kund, admin, support

  - [x] Databas tabeller
  - [x] Uppdatera `userSession` med en variabel för roller
  - [x] Implementera stöd för användarroller vid inloggning
  - [x] Ansätta en standard roll för nya användare

**Comment by Rickos99** [comment]
Förslag på användarroller:
```php
0: kund
1: support
2: admin
```
